# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lecture3/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Comp_27_0_0_1/design_1_Comp_27_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Comp_27_0_0 || ORIG_REF_NAME==design_1_Comp_27_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Counter_27_0_0_1/design_1_Counter_27_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Counter_27_0_0 || ORIG_REF_NAME==design_1_Counter_27_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rx_mod_0_0/design_1_rx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rx_mod_0_0 || ORIG_REF_NAME==design_1_rx_mod_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_divider_0_0/design_1_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_divider_0_0 || ORIG_REF_NAME==design_1_clk_divider_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LUT_0_0/design_1_LUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LUT_0_0 || ORIG_REF_NAME==design_1_LUT_0_0} -quiet] -quiet

# XDC: /home/esme/Desktop/VivadoProjects/EmbeddedSystems/UART_Gripper/UART_Gripper.gen/sources_1/bd/design_1/design_1_ooc.xdc
