# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const1.xdc

# Block Designs: bd/design_top/design_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top || ORIG_REF_NAME==design_top} -quiet] -quiet

# IP: bd/design_top/ip/design_top_CTRL_0_0/design_top_CTRL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_CTRL_0_0 || ORIG_REF_NAME==design_top_CTRL_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_Addr_Counter_0_0/design_top_Addr_Counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_Addr_Counter_0_0 || ORIG_REF_NAME==design_top_Addr_Counter_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_fsm_intr_0_0/design_top_fsm_intr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_fsm_intr_0_0 || ORIG_REF_NAME==design_top_fsm_intr_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_Addr_ctrl_0_0/design_top_Addr_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_Addr_ctrl_0_0 || ORIG_REF_NAME==design_top_Addr_ctrl_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_tx_mod_0_0/design_top_tx_mod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_tx_mod_0_0 || ORIG_REF_NAME==design_top_tx_mod_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_clk_divider_UART_0_0/design_top_clk_divider_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_clk_divider_UART_0_0 || ORIG_REF_NAME==design_top_clk_divider_UART_0_0} -quiet] -quiet

# IP: bd/design_top/ip/design_top_clk_divider_0_0/design_top_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_top_clk_divider_0_0 || ORIG_REF_NAME==design_top_clk_divider_0_0} -quiet] -quiet

# XDC: /home/esme/Desktop/VivadoProjects/EmbeddedSystems/IMU_SPI_UART/project_imu_spi_uart/project_imu_spi_uart.gen/sources_1/bd/design_top/design_top_ooc.xdc
